image: "python:3.5"

before_script:
  - python --version
  - pip install virtualenv

test:
  script:
    - pip3 install -r requirements.txt
    - nosetests --with-coverage --cover-tests --cover-erase --cover-package=tgdbapi
